name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
      logLevel:
        description: 'Log level'     
        required: false
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug
  push:
     branches: [ main,develop,'**' ]
  pull_request:
     branches: [ main,develop,'**' ]

jobs:
  dev_build:
    if: ${{ !(github.ref_name == 'main') || (inputs.enviroment != '') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: echo "${{ github.ref_name }}"		
      - name: Echo environment name
        run: echo "${{ inputs.environment }}"
  production_build:
    if: ${{ (github.ref_name == 'main') || (inputs.enviroment != '') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: echo "${{ github.ref_name }}"
      - name: Echo environment name
        run: echo "${{ inputs.environment }}"
