name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ main,develop,'**' ]
  pull_request:
    branches: [ main,develop,'**' ]

jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: echo "${{ github.ref_name }}"
